export const CREATE_TODO = 'CREATE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'

export const TOGGLE_TODO = 'TOGGLE_TODO'
export const FILTER_TODO = 'FILTER_TODO'

export const GET_TODO_LIST = 'GET_TODO_LIST'
export const CLEAR_TODOS_COMPETED = 'CLEAR_TODOS_COMPETED'
